apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ailab
resources:
- ingress.yaml
- ../base
images:
  - name: ghcr.io/botassist/n8n
    newTag: $IMAGE_TAG
configMapGenerator:
- name: botassist-n8n-config
  envs:
  - .env.vars

