---
apiVersion: v1
kind: Service
metadata:
  name: botassist-n8n
  namespace: ailab
  labels:
    app: botassist-n8n-main
spec:
  type: "ClusterIP"
  selector:
    app: botassist-n8n-main
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
      name: http

